In [ ]:
import pandas as pd
import psycopg2
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import seaborn as sns 
import statsmodels.stats.proportion as proportion
from scipy.stats import ttest_ind,mannwhitneyu,shapiro,norm
from statsmodels.stats.weightstats import ztest
from tqdm import tqdm
import timeit
from scipy import stats
from sqlalchemy import create_engine
import math
from datetime import date, datetime, timedelta
import time
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
import warnings
warnings.filterwarnings("ignore")


def get_engine(db_name):
    if db_name == antares_secret['dbname']:
        user = antares_secret['user']
        password = antares_secret['password']
        host = antares_secret['host']
        engine = create_engine(f'postgresql://{user}:{password}@{host}:5432/{db_name}')
    elif db_name == dwh_secret['dbname']:
        user = dwh_secret['user'] 
        password = dwh_secret['password']
        host = dwh_secret['host']
        engine = create_engine(f'postgresql://{user}:{password}@{host}:5432/{db_name}')
    return engine
        



def execute(SQL, db_name = 'dwh'):
    start_time = time.time()  # запоминаем время начала выполнения функции
    engine = get_engine(db_name)
    Session = sessionmaker(bind=engine)  # sessions factory ()
    with Session() as session: # open session
        result = session.execute(text(SQL))
        df = pd.DataFrame(result.fetchall(), columns=result.keys())
        
    end_time = time.time()  # запоминаем время окончания выполнения функции
    execution_time = end_time - start_time  # вычисляем время выполнения   
    
    print(f"Время выполнения функции: {execution_time} секунд")
    return df

In [2]:
import pandas as pd
import psycopg2
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import seaborn as sns 
import statsmodels.stats.proportion as proportion
from scipy.stats import ttest_ind,mannwhitneyu,shapiro,norm
from statsmodels.stats.weightstats import ztest
from tqdm import tqdm
import timeit
from scipy import stats
from sqlalchemy import create_engine
import math
from datetime import date, datetime, timedelta
import time
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
import warnings
warnings.filterwarnings("ignore")

from credential import postgres_secret,clickhouse_dwh_secret

def get_engine(user):
    if user == postgres_secret['user']:
        db_name = postgres_secret['db_name']
        password = postgres_secret['password']
        host = postgres_secret['host']
        engine = create_engine(f'postgresql://{user}:{password}@{host}:6432/{db_name}')
    elif user == clickhouse_dwh_secret['user']:
            db_name = clickhouse_dwh_secret['db_name'] 
            password = clickhouse_dwh_secret['password']
            host = clickhouse_dwh_secret['host']
            engine = create_engine(f'clickhouse://{user}:{password}@{host}:8123/{db_name}')
    return engine
    

    
def execute(SQL, user):
    start_time = time.time()  # запоминаем время начала выполнения функции
    engine = get_engine(user)
    Session = sessionmaker(bind=engine)  # sessions factory ()
    with Session() as session: # open session
        result = session.execute(text(SQL))
        df = pd.DataFrame(result.fetchall(), columns=result.keys())
        
    end_time = time.time()  # запоминаем время окончания выполнения функции
    execution_time = end_time - start_time  # вычисляем время выполнения   
    
    print(f"Время выполнения функции: {execution_time} секунд")
    return df

In [4]:
query = f''' SELECT * FROM invoices
             where id='588858b1-b9c2-4b79-8124-6d058e325361'
            '''

df = execute(query,user = 'kmekhtiev')
df.info()

Время выполнения функции: 0.6525959968566895 секунд
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1 non-null      object
 1   subscription_id         1 non-null      object
 2   payload                 1 non-null      object
 3   price_cents             1 non-null      int64
 4   price_currency          1 non-null      object
 5   paid_at                 1 non-null      datetime64[ns]
 6   period_end              1 non-null      datetime64[ns]
 7   transaction_id          1 non-null      object
 8   refunded_at             1 non-null      datetime64[ns]
 9   refund_amount_cents     1 non-null      int64
 10  refund_amount_currency  1 non-null      object
 11  payment_target          1 non-null      object
 12  deleted_at              1 non-null      datetime64[ns]
 13  created_at              1 non-null      datetime64[ns]
 14  updated_at              1 non-null      datetime64[ns]
 15  user_bonus_id           1 non-null      object
 16  state                   1 non-null      object
dtypes: datetime64[ns](6), int64(2), object(9)
memory usage: 268.0+ bytes

In [6]:
df

,id,subscription_id,payload,price_cents,price_currency,paid_at,period_end,transaction_id,refunded_at,refund_amount_cents,refund_amount_currency,payment_target,deleted_at,created_at,updated_at,user_bonus_id,state
0,588858b1-b9c2-4b79-8124-6d058e325361,19e82c1a-275a-47cb-b319-e11aff57ab0b,{},0,RUB,2023-09-14 03:14:49.608310,2023-10-22 14:56:35.702090,,1970-01-01,0,RUB,,1970-01-01,2023-09-22 14:56:35.729830,2023-09-22 14:56:35.729830,00000000-0000-0000-0000-000000000000,initial