In [146]:
from clickhouse_driver import Client
from tqdm import tqdm_notebook

In [148]:
client = Client(host='10.129.11.136', port='9000', user='superset', password='FmnaRL3cC6wnTkn', database='superset')

users pipeline

In [151]:
client.execute(''' 
CREATE TEMPORARY TABLE IF NOT EXISTS temp_renewal_table AS (
    select
        subscription_id,
        min(created_at) as renewal_off_date
    from product_x.subscription_cancel_reasons
    where created_at >= '2023-03-01'
    group by 1
)
''')
client.execute(''' 
truncate table temp_renewal_table
''')
client.execute(''' 
insert into temp_renewal_table
    select
        subscription_id,
        min(created_at) as renewal_off_date
    from product_x.subscription_cancel_reasons
    where created_at >= '2023-03-01'
    group by 1

''')
client.execute(''' 
CREATE TEMPORARY TABLE IF NOT EXISTS temp_device AS (
    select
    user_id,
    device_type,
    os
from
(
select
    user_id, 
    device_type,
    os,
    row_number() over(partition by user_id order by created_at) as rn
from product_x.devices
where
    created_at::date >= '2022-03-01'
) res
where rn = 1
)
''')
client.execute(''' 
truncate table temp_device
''')
client.execute(''' 
insert into temp_device
select
    user_id,
    device_type,
    os
from
(
select
    user_id, device_type, os,
    row_number() over(partition by user_id order by created_at) as rn
from product_x.devices
where
    created_at::date >= '2022-03-01'
) res
where rn = 1
''')
client.execute(''' 
truncate table datamarts.marketing_dash_local on cluster 'viasat_cluster'
''')
client.execute(''' 
truncate table datamarts.marketing_dash_distr on cluster 'viasat_cluster'
''')

[('dwh02', 9000, 0, '', 3, 0),
 ('dwh03', 9000, 0, '', 2, 0),
 ('dwh01', 9000, 0, '', 1, 0),
 ('dwh04', 9000, 0, '', 0, 0)]

In [152]:
# Упрощенная версия кода для генерации списка дат
from datetime import datetime

current_date = datetime.now()
current_year = current_date.year
current_month = current_date.month
start_year = 2022
end_year_month = (current_year, current_month)

dates = [f"{year}-{month:02d}" for year in range(start_year, end_year_month[0] + 1) 
                for month in range(1, 13) if (year, month) <= end_year_month]

In [153]:
client.execute(f''' 
    insert into
        datamarts.marketing_dash_distr
        select
            user_id,
            visitor_id,
            profile_id,
            reg_date,
            created_at,
            ends_at,
            renewal_off_date,
            state,
            price_cents,
            offer_duration,
            recurrent,
            bonus_title,
            promo,
            ub_type,
            money,
            bonus_activated_at,
            bonus_starts_at,
            bonus_ends_at,
            last_prolong_date,
            first_prolong_date,
            promo_type,
            coalesce(source.param_value, 'none') as reg_source,
            coalesce(campaign.param_value, 'none') as reg_campaign,
            coalesce(medium.param_value, 'none') as reg_medium,
            case
                when
                    (last_prolong_date is not null or last_prolong_date > '1970-01-01'
                    or ub_type = 'PromoCodes::Discount::Bonus'
                    )
                    AND arrayExists(x -> x NOT IN (0, 100), money)
            then
                1
            else
                0
            end as payer,
            len as len,
            device_type as device,
            u.deleted_at as deleted_at,
            platform,
            domain_locale,
            first_payment,
            s.trial_duration as trial_duration,
            s.trial_duration_unit astrial_duration_unit,
            os as device_os,
            CASE 
                WHEN ub_type = 'PromoCodes::WithBindingCard::Bonus'
                    AND (bonus_ends_at - bonus_starts_at) BETWEEN 28 AND 32
                THEN 30
                WHEN ub_type = 'PromoCodes::WithBindingCard::Bonus'
                    AND (bonus_ends_at - bonus_starts_at) BETWEEN 33 AND 37
                THEN 35
                WHEN ub_type = 'PromoCodes::WithBindingCard::Bonus'
                    AND (bonus_ends_at - bonus_starts_at) BETWEEN 40 AND 47
                THEN 45
                WHEN ub_type = 'PromoCodes::WithBindingCard::Bonus'
                    AND (bonus_ends_at - bonus_starts_at) BETWEEN 58 AND 63
                THEN 60
                WHEN ub_type = 'PromoCodes::WithBindingCard::Bonus'
                    AND (bonus_ends_at - bonus_starts_at) BETWEEN 80 AND 95
                THEN 90
                WHEN promo_type = 'cards'
                    AND created_at::date = bonus_activated_at::date 
                    AND ub_type != 'PromoCodes::WithBindingCard::Bonus'
                THEN 0
                WHEN promo_type != 'promo'
                    AND state IN ('trial', 'normal_period', 'canceled', 'grace_period')
                    AND (price_cents = 299 OR price_cents < 29900 OR price_cents = 29900)
                THEN 14
                WHEN promo_type != 'promo'
                    AND state IN ('trial', 'normal_period', 'canceled', 'grace_period')
                    AND price_cents > 29900
                THEN 3
                WHEN state not IN ('trial', 'normal_period', 'canceled', 'grace_period') 
                THEN 0
                else ends_at::date - created_at::date
            END AS free_days
    from (
            select
                u.id as user_id,
                s.id as sub_id,
                u.visitor_id as visitor_id,
                p.id as profile_id,
                source.param_value,
                campaign.param_value,
                medium.param_value,
                u.created_at::date as reg_date,
                s.created_at as created_at,
                s.ends_at as ends_at,
                renewal_off_date,
                s.state as state,
                s.price_cents as price_cents,
                concat(s.duration, ' ', s.duration_unit) as offer_duration,
                s.recurrent as recurrent,
                bp.title as bonus_title,
                pc.title as promo,
                pca.multiple,
                ub.activated_at::date as bonus_activated_at,
                ub.starts_at::date as bonus_starts_at,
                ub.type as ub_type,
                ub.ends_at::date as bonus_ends_at,
                CASE
                    WHEN len > 0 AND arrayExists(x -> x NOT IN (0, 1, 100), money)
                    THEN 
                        r.pays_reversed[1]::date
                    WHEN ub_type = 'PromoCodes::Discount::Bonus' AND arrayExists(x -> x NOT IN (0, 1, 100), money)
                    then 
                        r.pays_reversed[1]::date
                    ELSE NULL
                END as last_prolong_date,
                CASE
                    WHEN len > 0 AND arrayExists(x -> x NOT IN (0, 1, 100), money)
                    THEN 
                        r.pays[2]::date
                    when ub_type = 'PromoCodes::Discount::Bonus' AND arrayExists(x -> x NOT IN (0, 1, 100), money)
                    then 
                        r.pays[1]::date
                    ELSE NULL
                END as first_prolong_date,
                CASE
                    WHEN 
                        pc.title IS NULL 
                        OR pc.title = '' 
                        OR ub_type IS NULL 
                        OR ub_type = ''
                    THEN 
                        'no_promo'
                    WHEN 
                        bp.title  ILIKE '%%гудпринт%%' OR 
                        bp.title  ILIKE '%%город_тройка%%' OR 
                        bp.title  ILIKE '%%фильмы и сериалы по подписке (магнит)%%' OR
                        bp.title IN (
                            'Для приложения Кошелёк', 
                            'фильмы и сериалы по подписке для промокодов3мес за 399руб (Адмитад)', 
                            'ГородТройка', 
                            'Подписка_viju_1мес_Город_29июля', 
                            'Подписка_viju_1_месяцев_RuTube_24окт', 
                            'Подписка_viju_45_дней_Промо_МВидео', 
                            '100 промокодов на подарки'
                            )
                        OR ub_type = 'PromoCodes::Bonus'
                    THEN 
                        'cards'
                    WHEN 
                        (ub_type IS NOT NULL AND ub_type != '') AND
                        ub_type NOT IN ('PromoCodes::Bonus', 'PromoCodes::FixDate::Bonus', 'UserAdjustmentBonus', 'UserInvitationBonus', 'UserReferralBonus') 
                        AND 
                        bp.title NOT ILIKE '%%гудпринт%%' AND
                        bp.title NOT ILIKE '%%город_тройка%%' AND
                        bp.title NOT ILIKE '%%фильмы и сериалы по подписке (магнит)%%'
                    THEN 
                        'promo'
                    ELSE
                        'no_promo'
                END AS promo_type,
                row_number() over(partition by user_id order by ub.starts_at::date desc) as bonus_num,
                money,
                len,
                device_type,
                u.deleted_at,
                s.platform as platform,
                u.domain_locale as domain_locale,
                arrayFirst(x -> x > 100, money) AS first_payment,
                s.trial_duration,
                s.trial_duration_unit,
                os
            from product_x.users u
            left join
            (select
                id,
                user_id,
                created_at,
                ends_at,
                state,
                price_cents,
                recurrent,
                cast(duration as text) as duration,
                platform,
                duration_unit,
                trial_duration,
                trial_duration_unit,
                row_number() over(partition by user_id order by created_at desc) as rn
            from product_x.subscriptions s
            where
                (state in  ('normal_period','canceled','trial','grace_period')
                and s.created_at::date >= '2022-01-01')
            ) s
                on (s.user_id = u.id and s.rn = 1)
            left join product_x.profiles p
                on (p.user_id = u.id and p.kind= 'main')
            left join
            (
                SELECT  
                    s2.id,
                    arraySort(
                        arrayDistinct(
                            arrayFilter(
                                x -> x != '1970-01-01',
                                groupArray(paid_at::date)
                            )
                        )
                    ) AS pays,
                    arrayReverse(
                        arraySort(
                            arrayDistinct(
                                arrayFilter(
                                    x -> x != '1970-01-01',
                                    groupArray(paid_at::date)
                                )
                            )
                        )
                    ) AS pays_reversed,
                    arraySort(
                        arrayDistinct(
                            groupArray(i2.price_cents)
                        )
                    ) AS money,
                    length(
                        arraySort(
                            arrayDistinct(
                                arrayFilter(
                                    x -> x != '1970-01-01',
                                    groupArray(paid_at::date)
                                )
                            )
                        )
                    ) - 1 AS len
                FROM 
                    product_x.subscriptions s2
                LEFT JOIN 
                    product_x.invoices i2 
                    ON i2.subscription_id = s2.id  
                WHERE
                    state IN ('normal_period', 'canceled', 'trial', 'grace_period')
                    AND s2.created_at::date >= '2022-01-01'
                    AND i2.paid_at::date > '1970-01-01'
                    AND i2.state IN ('success', 'refunded')
                GROUP BY 
                    s2.id
            ) r
                on r.id = s.id
            left join
                   (
                   select 
                        id, 
                        deleted_at,
                        type,
                        subscription_id, 
                        activated_at, 
                        starts_at, 
                        ends_at,
                        status,
                        row_number() over(partition by subscription_id order by activated_at asc) as rn
                   from product_x.user_bonuses 
                   where 
                        status= 'activated'
                   ) ub 
                on (ub.subscription_id = s.id 
                    and (ub.activated_at::date != '1970-01-01' or ub.activated_at is not null)
                    and ub.status='activated' and ub.rn = 1 and ub.subscription_id != '00000000-0000-0000-0000-000000000000')
            left join product_x.promo_code_activations pca
                on pca.user_bonus_id = ub.id 
            left join product_x.promo_codes pc
                on pc.id = pca.promo_code_id and pc.deleted_at:: date = '1970-01-01'
            left join product_x.bonus_programs bp
                on bp.id = pc.bonus_program_id and bp.deleted_at:: date = '1970-01-01'
            left join
            (
                    select
                        param_value,
                        user_id,
                        usp.created_at as utm_created,
                        row_number() over(partition by user_id, parameter_id order by usp.created_at) as order
                    from
                        product_x.user_parameters usp
                        left join product_x.dictionaries_parameters dp
                        on dp.id = usp.parameter_id
                    where
                        dp.title = 'utm_source'
            )source on source.user_id = u.id and source.order = 1
            left join
            (
                    select
                        param_value,
                        user_id,
                        usp.created_at as utm_created,
                        row_number() over(partition by user_id, parameter_id order by usp.created_at) as order
                    from
                        product_x.user_parameters usp
                        left join product_x.dictionaries_parameters dp
                        on dp.id = usp.parameter_id
                    where
                        dp.title = 'utm_campaign'
            )campaign on campaign.user_id = u.id and campaign.order = 1
            left join
            (
                    select
                        param_value,
                        user_id,
                        usp.created_at as utm_created,
                        row_number() over(partition by user_id, parameter_id order by usp.created_at) as order
                    from
                        product_x.user_parameters usp
                        left join product_x.dictionaries_parameters dp
                        on dp.id = usp.parameter_id
                    where
                        dp.title = 'utm_medium'
            )medium on medium.user_id = u.id and medium.order = 1
            left join temp_renewal_table trt
                on trt.subscription_id = s.id
            left join temp_device td
                on td.user_id = u.id
            where
                u.user_type = 'regular'
                and 
                (
                    (u.email NOT ILIKE '%%@test%%' AND u.email NOT ILIKE '%%@viasat%%')
                    OR
                    (u.email IS NULL AND u.phone_number IS NOT NULL)
                )
                and u.vipplay = FALSE
                and u.created_at::date >= '2022-01-01'
        ) res
        where bonus_num = 1
    ''')

[]

events_pipeline with deduplication

In [155]:
client.execute(''' 
truncate table datamarts.streaming_events_correction_distr on cluster 'viasat_cluster'
''')
client.execute(''' 
truncate table datamarts.streaming_events_correction_local on cluster 'viasat_cluster' 
''')

[('dwh03', 9000, 0, '', 3, 2),
 ('dwh04', 9000, 0, '', 2, 2),
 ('dwh02', 9000, 0, '', 1, 0),
 ('dwh01', 9000, 0, '', 0, 0)]

In [156]:
days = [(270,210),(209,181),(180,140),(139,120),(119,70),(69,40),(39,0)]

In [157]:
for day in tqdm_notebook(days):
    client.execute(f'''
    insert into datamarts.streaming_events_correction_distr
    select *
    from
        (
                select
                id,
                utc_timestamp,
                utc_timestamp::date as date,
                user_timezone,
                user_id as user_id,
                visitor_id as visitor_id,
                profile_id as profile_id,
                session_id,
                item_id,
                model_type,
                client_type,
                event_name,
                event_page,
                device_type,
                payload,
                session_order,
                IF(event_name = 'auto_player_streaming',
                    ROW_NUMBER() OVER (
                        PARTITION BY user_id, utc_timestamp, event_name),
                    1) AS rn,
                '1970-01-01'::date as deleted_at,
                os_version,
                browser_version,
                app_version,
                country
    from
        superset.events_distr
    where
        cast(utc_timestamp as date) between addDays(toDate(today()), -{day[0]}) and addDays(toDate(today()), -{day[1]})
    and 
        event_name not ilike '%%partner%%'
    and 
        (
            (event_name != 'auto_player_streaming') 
            OR 
            (event_name = 'auto_player_streaming' AND JSONExtractFloat(payload, 'viewing_time')::float <= 86000)
        )
    )
    where rn = 1
    ''')

/var/folders/sl/4slwjbhd1rz6q3665v1k847c0000gn/T/ipykernel_67669/935364656.py:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for day in tqdm_notebook(days):

  0%|          | 0/7 [00:00<?, ?it/s]

In [158]:
client.execute(''' 
truncate table datamarts.sandbox_data_local on cluster 'viasat_cluster'

''')
client.execute(''' 
truncate table datamarts.sandbox_data_distr on cluster 'viasat_cluster'
''')

client.execute(''' 
insert into datamarts.sandbox_data_distr
select
        aet.id as id,
        utc_timestamp,
        utc_timestamp::date as date,
        user_timezone,
        aet.user_id as user_id,
        aet.visitor_id as visitor_id,
        aet.profile_id as profile_id,
        session_id,
        item_id,
        model_type,
        case when client_type ilike '%ios%'
            then
                'ios'
            when client_type = 'web' 
            then
                'web_desktop'
            when client_type ilike '%smart%'
            then
                'smart_tv'
            else
                client_type
        end as client_type,
        event_name,
        event_page,
        device_type,
        payload,
        session_order,
        coalesce(   
        replaceAll(
        replaceAll(splitByChar(Char(39),assumeNotNull(extractURLParameter(payload, 'utm_source')))[1]
        ,'}',''
        ),'"','') 
        ,'none') as source,
        coalesce(   
        replaceAll(
        replaceAll(splitByChar(Char(39),assumeNotNull(extractURLParameter(payload, 'utm_campaign')))[1]
        ,'}',''
        ),'"','') 
        ,'none') as campaign,
        mk.user_id as user_id_back,
        mk.visitor_id as visitor_id_back,
        mk.profile_id as profile_id_back,
        mk.reg_date as reg_date,
        mk.created_at as created_at,
        mk.ends_at as ends_at,
        renewal_off_date,
        state,
        price_cents,
        offer_duration,
        recurrent,
        bonus_title,
        promo,
        ub_type,
        money,
        bonus_activated_at,
        bonus_starts_at,
        bonus_ends_at,
        last_prolong_date,
        first_prolong_date,
        promo_type,
        reg_source,
        reg_campaign,
        reg_medium,
        payer,
        len,
        device,
        os_version,
        browser_version,
        app_version,    
        country,
        trial_duration,
        trial_duration_unit
from datamarts.streaming_events_correction_distr aet
left join datamarts.marketing_dash_distr mk on
    (mk.profile_id = aet.profile_id)
--where 
    --cast(aet.utc_timestamp as date) >= addDays(toDate(today()), -180)
    --and event_name not ilike '%partner%'
''')

[]

In [159]:
client.execute(''' 
truncate table datamarts.dash_table_local on cluster 'viasat_cluster'

''')
client.execute(''' 
truncate table datamarts.dash_table_distr on cluster 'viasat_cluster'
''')

client.execute(''' 
insert into datamarts.dash_table_distr
select
        aet.id as id,
        utc_timestamp,
        utc_timestamp::date as date,
        user_timezone,
        aet.user_id as user_id,
        aet.visitor_id as visitor_id,
        aet.profile_id as profile_id,
        session_id,
        item_id,
        model_type,
        case when client_type ilike '%ios%'
            then
                'ios'
            when client_type = 'web' 
            then
                'web_desktop'
            when client_type ilike '%smart%'
            then
                'smart_tv'
            else
                client_type
        end as client_type,
        event_name,
        event_page,
        device_type,
        payload,
        session_order,
        coalesce(   
        replaceAll(
        replaceAll(splitByChar(Char(39),assumeNotNull(extractURLParameter(payload, 'utm_source')))[1]
        ,'}',''
        ),'"','') 
        ,'none') as source,
        coalesce(   
        replaceAll(
        replaceAll(splitByChar(Char(39),assumeNotNull(extractURLParameter(payload, 'utm_campaign')))[1]
        ,'}',''
        ),'"','') 
        ,'none') as campaign,
        mk.user_id as user_id_back,
        mk.visitor_id as visitor_id_back,
        mk.profile_id as profile_id_back,
        mk.reg_date as reg_date,
        mk.created_at as created_at,
        mk.ends_at as ends_at,
        renewal_off_date,
        state,
        price_cents,
        offer_duration,
        recurrent,
        bonus_title,
        promo,
        ub_type,
        money,
        bonus_activated_at,
        bonus_starts_at,
        bonus_ends_at,
        last_prolong_date,
        first_prolong_date, 
        promo_type,
        reg_source,
        reg_campaign,
        reg_medium,
        payer,
        len,
        device,
        os_version,
        browser_version,
        app_version,    
        country,
        trial_duration,
        trial_duration_unit,
        device_os
from datamarts.streaming_events_correction_distr aet
left join datamarts.marketing_dash_distr mk on
    (mk.profile_id = aet.profile_id)
where 
    cast(aet.utc_timestamp as date) >= addDays(toDate(today()), -180)
''')

[]

In [160]:
client.execute(''' 
truncate table datamarts.streaming_events_correction_distr on cluster 'viasat_cluster'
''')
client.execute(''' 
truncate table datamarts.streaming_events_correction_local on cluster 'viasat_cluster' 
''')

[('dwh03', 9000, 0, '', 3, 2),
 ('dwh04', 9000, 0, '', 2, 2),
 ('dwh02', 9000, 0, '', 1, 0),
 ('dwh01', 9000, 0, '', 0, 0)]